---
- name: Initialize first Kubernetes master
  hosts: main-master
  become: true
  vars_files:
    - /etc/ansible/haproxy.yml
  tasks:
    - name: Initialize Kubernetes Master
      command: >
        kubeadm init
        --control-plane-endpoint={{ haproxy_1 }}:6443
        --pod-network-cidr=192.168.0.0/16
        --cri-socket=/run/cri-dockerd.sock
        --upload-certs
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Save kubeadm init output to control node
      local_action:
        copy content="{{ kubeadm_init.stdout }}" dest="/tmp/kubeadm-init.out"

    - name: make directory and copy required file to it
      shell: |
        sudo su -c 'mkdir -p $HOME/.kube' ubuntu
        sudo su -c 'sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config' ubuntu
        sudo su -c 'sudo chown $(id -u):$(id -g) $HOME/.kube/config' ubuntu

    - name: Fetch kubeconfig to Ansible control node
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/config
        flat: true

